name: Deploy to AWS

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment to deploy (dev or prod)'
        required: true
        type: choice
        options:
          - dev
          - prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r infra/requirements.txt
      - name: CDK Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
          CIVIC_API_KEY: ${{ secrets.CIVIC_API_KEY }}
          DEPLOY_ENV: ${{ github.event.inputs.environment }}
        run: |
          cdk -a "python infra/app.py" deploy --require-approval never

